language: ruby

services:
  - redis-server
  - postgresql

before_install:
  - sudo service redis-server start

before_script:
  - nvm install stable
  - npm install -g yarn
  - bin/yarn
  - cp config/redis.yml.example config/redis.yml
  - bin/rake db:create

cache:
  timeout: 1200
  yarn: true

  directories:
    - node_modules
