export { default as Details } from './Details.vue'
export { default as DetailsItem } from './DetailsItem.vue'
export { default as DetailsLabel } from './DetailsLabel.vue'
export { default as DetailsContent } from './DetailsContent.vue'
export * from './types'
