/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/dashboard/': RouteRecordInfo<'/dashboard/', '/dashboard', Record<never, never>, Record<never, never>>,
    '/dashboard/issues': RouteRecordInfo<'/dashboard/issues', '/dashboard/issues', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/profile/basic': RouteRecordInfo<'/profile/basic', '/profile/basic', Record<never, never>, Record<never, never>>,
    '/profile/projects/[project_id]': RouteRecordInfo<'/profile/projects/[project_id]', '/profile/projects/:project_id', { project_id: ParamValue<true> }, { project_id: ParamValue<false> }>,
    '/projects/': RouteRecordInfo<'/projects/', '/projects', Record<never, never>, Record<never, never>>,
    '/projects/[project_id]/': RouteRecordInfo<'/projects/[project_id]/', '/projects/:project_id', { project_id: ParamValue<true> }, { project_id: ParamValue<false> }>,
    '/projects/[project_id]/analytics/': RouteRecordInfo<'/projects/[project_id]/analytics/', '/projects/:project_id/analytics', { project_id: ParamValue<true> }, { project_id: ParamValue<false> }>,
    '/projects/[project_id]/analytics/issue_activity_chart': RouteRecordInfo<'/projects/[project_id]/analytics/issue_activity_chart', '/projects/:project_id/analytics/issue_activity_chart', { project_id: ParamValue<true> }, { project_id: ParamValue<false> }>,
    '/projects/[project_id]/analytics/issue_creator_chart': RouteRecordInfo<'/projects/[project_id]/analytics/issue_creator_chart', '/projects/:project_id/analytics/issue_creator_chart', { project_id: ParamValue<true> }, { project_id: ParamValue<false> }>,
    '/projects/[project_id]/categories/': RouteRecordInfo<'/projects/[project_id]/categories/', '/projects/:project_id/categories', { project_id: ParamValue<true> }, { project_id: ParamValue<false> }>,
    '/projects/[project_id]/categories/[category_id].edit': RouteRecordInfo<'/projects/[project_id]/categories/[category_id].edit', '/projects/:project_id/categories/:category_id/edit', { project_id: ParamValue<true>, category_id: ParamValue<true> }, { project_id: ParamValue<false>, category_id: ParamValue<false> }>,
    '/projects/[project_id]/categories/new': RouteRecordInfo<'/projects/[project_id]/categories/new', '/projects/:project_id/categories/new', { project_id: ParamValue<true> }, { project_id: ParamValue<false> }>,
    '/projects/[project_id]/issue_templates/': RouteRecordInfo<'/projects/[project_id]/issue_templates/', '/projects/:project_id/issue_templates', { project_id: ParamValue<true> }, { project_id: ParamValue<false> }>,
    '/projects/[project_id]/issue_templates/[issue_template_id].edit': RouteRecordInfo<'/projects/[project_id]/issue_templates/[issue_template_id].edit', '/projects/:project_id/issue_templates/:issue_template_id/edit', { project_id: ParamValue<true>, issue_template_id: ParamValue<true> }, { project_id: ParamValue<false>, issue_template_id: ParamValue<false> }>,
    '/projects/[project_id]/issue_templates/new': RouteRecordInfo<'/projects/[project_id]/issue_templates/new', '/projects/:project_id/issue_templates/new', { project_id: ParamValue<true> }, { project_id: ParamValue<false> }>,
    '/projects/[project_id]/issues/': RouteRecordInfo<'/projects/[project_id]/issues/', '/projects/:project_id/issues', { project_id: ParamValue<true> }, { project_id: ParamValue<false> }>,
    '/projects/[project_id]/issues/[issue_id]/': RouteRecordInfo<'/projects/[project_id]/issues/[issue_id]/', '/projects/:project_id/issues/:issue_id', { project_id: ParamValue<true>, issue_id: ParamValue<true> }, { project_id: ParamValue<false>, issue_id: ParamValue<false> }>,
    '/projects/[project_id]/issues/[issue_id]/merge': RouteRecordInfo<'/projects/[project_id]/issues/[issue_id]/merge', '/projects/:project_id/issues/:issue_id/merge', { project_id: ParamValue<true>, issue_id: ParamValue<true> }, { project_id: ParamValue<false>, issue_id: ParamValue<false> }>,
    '/projects/[project_id]/issues/[issue_id]/migrate': RouteRecordInfo<'/projects/[project_id]/issues/[issue_id]/migrate', '/projects/:project_id/issues/:issue_id/migrate', { project_id: ParamValue<true>, issue_id: ParamValue<true> }, { project_id: ParamValue<false>, issue_id: ParamValue<false> }>,
    '/projects/[project_id]/issues/[issue_id].edit': RouteRecordInfo<'/projects/[project_id]/issues/[issue_id].edit', '/projects/:project_id/issues/:issue_id/edit', { project_id: ParamValue<true>, issue_id: ParamValue<true> }, { project_id: ParamValue<false>, issue_id: ParamValue<false> }>,
    '/projects/[project_id]/issues/new': RouteRecordInfo<'/projects/[project_id]/issues/new', '/projects/:project_id/issues/new', { project_id: ParamValue<true> }, { project_id: ParamValue<false> }>,
    '/projects/[project_id]/members/': RouteRecordInfo<'/projects/[project_id]/members/', '/projects/:project_id/members', { project_id: ParamValue<true> }, { project_id: ParamValue<false> }>,
    '/projects/[project_id]/members/[member_id].edit': RouteRecordInfo<'/projects/[project_id]/members/[member_id].edit', '/projects/:project_id/members/:member_id/edit', { project_id: ParamValue<true>, member_id: ParamValue<true> }, { project_id: ParamValue<false>, member_id: ParamValue<false> }>,
    '/projects/[project_id]/members/new': RouteRecordInfo<'/projects/[project_id]/members/new', '/projects/:project_id/members/new', { project_id: ParamValue<true> }, { project_id: ParamValue<false> }>,
    '/projects/[project_id]/milestones/': RouteRecordInfo<'/projects/[project_id]/milestones/', '/projects/:project_id/milestones', { project_id: ParamValue<true> }, { project_id: ParamValue<false> }>,
    '/projects/[project_id]/milestones/[milestone_id].edit': RouteRecordInfo<'/projects/[project_id]/milestones/[milestone_id].edit', '/projects/:project_id/milestones/:milestone_id/edit', { project_id: ParamValue<true>, milestone_id: ParamValue<true> }, { project_id: ParamValue<false>, milestone_id: ParamValue<false> }>,
    '/projects/[project_id]/milestones/new': RouteRecordInfo<'/projects/[project_id]/milestones/new', '/projects/:project_id/milestones/new', { project_id: ParamValue<true> }, { project_id: ParamValue<false> }>,
    '/projects/[project_id]/plans/': RouteRecordInfo<'/projects/[project_id]/plans/', '/projects/:project_id/plans', { project_id: ParamValue<true> }, { project_id: ParamValue<false> }>,
    '/projects/[project_id]/plans/[plan_id]': RouteRecordInfo<'/projects/[project_id]/plans/[plan_id]', '/projects/:project_id/plans/:plan_id', { project_id: ParamValue<true>, plan_id: ParamValue<true> }, { project_id: ParamValue<false>, plan_id: ParamValue<false> }>,
    '/projects/[project_id]/plans/[plan_id].edit': RouteRecordInfo<'/projects/[project_id]/plans/[plan_id].edit', '/projects/:project_id/plans/:plan_id/edit', { project_id: ParamValue<true>, plan_id: ParamValue<true> }, { project_id: ParamValue<false>, plan_id: ParamValue<false> }>,
    '/projects/[project_id]/platforms/': RouteRecordInfo<'/projects/[project_id]/platforms/', '/projects/:project_id/platforms', { project_id: ParamValue<true> }, { project_id: ParamValue<false> }>,
    '/projects/[project_id]/platforms/[platform_id].edit': RouteRecordInfo<'/projects/[project_id]/platforms/[platform_id].edit', '/projects/:project_id/platforms/:platform_id/edit', { project_id: ParamValue<true>, platform_id: ParamValue<true> }, { project_id: ParamValue<false>, platform_id: ParamValue<false> }>,
    '/projects/[project_id]/platforms/new': RouteRecordInfo<'/projects/[project_id]/platforms/new', '/projects/:project_id/platforms/new', { project_id: ParamValue<true> }, { project_id: ParamValue<false> }>,
    '/projects/[project_id]/storyboards/': RouteRecordInfo<'/projects/[project_id]/storyboards/', '/projects/:project_id/storyboards', { project_id: ParamValue<true> }, { project_id: ParamValue<false> }>,
    '/projects/[project_id]/storyboards/[storyboard_id]': RouteRecordInfo<'/projects/[project_id]/storyboards/[storyboard_id]', '/projects/:project_id/storyboards/:storyboard_id', { project_id: ParamValue<true>, storyboard_id: ParamValue<true> }, { project_id: ParamValue<false>, storyboard_id: ParamValue<false> }>,
    '/projects/[project_id]/test_case_labels/': RouteRecordInfo<'/projects/[project_id]/test_case_labels/', '/projects/:project_id/test_case_labels', { project_id: ParamValue<true> }, { project_id: ParamValue<false> }>,
    '/projects/[project_id]/test_case_labels/[test_case_label_id].edit': RouteRecordInfo<'/projects/[project_id]/test_case_labels/[test_case_label_id].edit', '/projects/:project_id/test_case_labels/:test_case_label_id/edit', { project_id: ParamValue<true>, test_case_label_id: ParamValue<true> }, { project_id: ParamValue<false>, test_case_label_id: ParamValue<false> }>,
    '/projects/[project_id]/test_case_labels/new': RouteRecordInfo<'/projects/[project_id]/test_case_labels/new', '/projects/:project_id/test_case_labels/new', { project_id: ParamValue<true> }, { project_id: ParamValue<false> }>,
    '/projects/[project_id]/test_cases/': RouteRecordInfo<'/projects/[project_id]/test_cases/', '/projects/:project_id/test_cases', { project_id: ParamValue<true> }, { project_id: ParamValue<false> }>,
    '/projects/[project_id].edit': RouteRecordInfo<'/projects/[project_id].edit', '/projects/:project_id/edit', { project_id: ParamValue<true> }, { project_id: ParamValue<false> }>,
    '/projects/new': RouteRecordInfo<'/projects/new', '/projects/new', Record<never, never>, Record<never, never>>,
    '/users/': RouteRecordInfo<'/users/', '/users', Record<never, never>, Record<never, never>>,
    '/users/[user_id].edit': RouteRecordInfo<'/users/[user_id].edit', '/users/:user_id/edit', { user_id: ParamValue<true> }, { user_id: ParamValue<false> }>,
    '/users/new': RouteRecordInfo<'/users/new', '/users/new', Record<never, never>, Record<never, never>>,
  }
}
