name: Rails

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    services:
      postgres:
        image: postgres:12
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        env: { POSTGRES_PASSWORD: postgres }

      redis:
        image: redis:6
        ports: ["6379:6379"]

      memcached:
        image: memcached:1.6
        ports: ["11211:11211"]

    steps:
      - uses: actions/checkout@v4
      - run: ./setup.sh

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'

      - run: pnpm install

      - run: ./prepare.sh
      - run: ./test.sh
      # - run: bundle exec rake coverage
      # - uses: actions/upload-artifact@v4
      #   if: failure()
      #   with: { name: coverage, path: ./coverage }
